version: '3'

vars:
  APP_NAME: my-app
  VERSION: "1.0.0"
  BUILD_DIR: ./build

tasks:
  build:
    desc: Build with status checking
    dir: "{{.BUILD_DIR}}"
    status:
      - test -f "{{.APP_NAME}}-{{.VERSION}}"
    sources:
      - "src/**/*.go"
    generates:
      - "{{.BUILD_DIR}}/{{.APP_NAME}}-{{.VERSION}}"
    cmds:
      - "echo 'Building {{.APP_NAME}} v{{.VERSION}}'"
