package transparent

import (
	"fmt"
	"reflect"
)

// VarOrigin identifies where a variable was defined.
type VarOrigin int

const (
	OriginEnvironment          VarOrigin = iota // OS environment variable
	OriginSpecial                               // Built-in: TASK, ROOT_DIR, etc.
	OriginTaskfileEnv                           // Taskfile.yml env: block
	OriginTaskfileVars                          // Taskfile.yml vars: block
	OriginIncludeVars                           // Include directive vars
	OriginIncludedTaskfileVars                  // Vars from included Taskfile
	OriginCallVars                              // CLI or call-site vars
	OriginTaskVars                              // Task-level vars: block
	OriginForLoop                               // FOR loop iterator (ITEM, KEY)
	OriginDotenv                                // .env file
)

// String returns a human-readable label for the origin.
func (o VarOrigin) String() string {
	switch o {
	case OriginEnvironment:
		return "environment"
	case OriginSpecial:
		return "special"
	case OriginTaskfileEnv:
		return "taskfile:env"
	case OriginTaskfileVars:
		return "taskfile:vars"
	case OriginIncludeVars:
		return "include:vars"
	case OriginIncludedTaskfileVars:
		return "included:taskfile:vars"
	case OriginCallVars:
		return "call:vars"
	case OriginTaskVars:
		return "task:vars"
	case OriginForLoop:
		return "for:loop"
	case OriginDotenv:
		return "dotenv"
	default:
		return fmt.Sprintf("unknown(%d)", int(o))
	}
}

// VarTrace captures a single variable resolution event.
type VarTrace struct {
	Name       string    // Variable name
	Value      any       // Resolved value
	RawValue   any       // Pre-template-substitution value (nil if same as Value)
	Origin     VarOrigin // Where the variable was defined
	Type       string    // Go type string
	IsDynamic  bool      // True if resolved via sh:
	ShCmd      string    // Shell command (if dynamic)
	Dir        string    // Directory context
	ShadowsVar *VarTrace // Non-nil if this var shadows another from outer scope
	TaskName   string    // Empty for global scope
	IsRef      bool      // True if defined via ref: keyword
	RefName    string    // Source variable name for ref vars
	ValueID    uintptr   // reflect pointer for slice/map identity; 0 for scalars
	Extra      map[string]any // Extensibility field for IDE plugins and future use
}

// ComputeValueID sets the ValueID field based on the Value's reflect pointer.
// For slice/map/pointer types, this allows detecting shared instances.
func (vt *VarTrace) ComputeValueID() {
	if vt.Value == nil {
		vt.ValueID = 0
		return
	}
	rv := reflect.ValueOf(vt.Value)
	switch rv.Kind() {
	case reflect.Slice, reflect.Map, reflect.Ptr:
		if !rv.IsNil() {
			vt.ValueID = rv.Pointer()
		}
	}
}

// TypeString returns the Go type of the value as a string.
func TypeString(v any) string {
	if v == nil {
		return "nil"
	}
	return fmt.Sprintf("%T", v)
}

// PipeStep captures one step in a template pipe chain.
type PipeStep struct {
	FuncName   string   // Function name: "printf", "trim"
	Args       []string // Raw arguments: ["\"%s\"", ".NAME"]
	ArgsValues []string // Resolved arguments: ["\"%s\"", "\"hello\""]
	Output     string   // Intermediate result after this step
}

// TemplateTrace captures one template evaluation.
type TemplateTrace struct {
	Input    string     // Raw template string
	Output   string     // Resolved output
	Context  string     // Where used: "task:build.cmds[0]"
	Steps    []PipeStep // Pipe chain breakdown
	VarsUsed []string   // Variable names referenced
	Error    string     // Template error if any
}

// CmdTrace captures a single command before/after template substitution.
type CmdTrace struct {
	Index          int
	RawCmd         string          // Before substitution
	ResolvedCmd    string          // After substitution
	Templates      []TemplateTrace // Template evaluations within this command
	IterationLabel string          // Non-empty for FOR-loop expanded commands
}

// TaskTrace groups all traces for a single task.
type TaskTrace struct {
	TaskName  string
	Vars      []VarTrace
	Templates []TemplateTrace
	Deps      []string
	Cmds      []CmdTrace
}

// TraceReport is the top-level report generated by the tracer.
type TraceReport struct {
	GlobalVars []VarTrace
	Tasks      []*TaskTrace
}
